### ISSUE TITLE
Bibtex citekey is random UUID

### ISSUE THREAD

**Issue by mfenner** [datacite/content-resolver#4]
The random UUID in the citation key is not stable, making it impossible to reuse.

https://github.com/datacite/content-resolver/blob/master/src/main/resources/freemarker/doi_bibtex.ftl

**Comment by dhimmel** [comment]
Perhaps the UUID should be the [short DOI](http://shortdoi.org/).

**Comment by mfenner** [comment]
For the bibtex that DataCIte pushes to ORCID we are now using the DOI (as expressed as URL) as citation key. We are doing the same in the DataCite blog. Short DOI is also nice, but an extra step. (Note: I work for DataCite since last year).

**Comment by dhimmel** [comment]
> Short DOI is also nice, but an extra step.

This should work is all DOIs are valid BibTeX citation keys.

> For the bibtex that DataCIte pushes to ORCID we are now using the DOI (as expressed as URL) as citation key.

I'm not convinced the problem has been fixed. For example, when I look up a Zenodo DOI on doi2bib.org, I still get a random citation key ([example](http://www.doi2bib.org/#/doi/10.5281/zenodo.48810 "doi2bib for DOI: 10.5281/zenodo.48810")). In addition, Zenodo DOIs have trouble importing into Authorea. Below, I've copied the issue I [filed with](https://www.authorea.com/issues/548 "Zenodo DOIs do not import properly") Authorea:

***

I'm having issues with the display format of Zenodo records. We'll use a specific record as an example. Suppose I want to reference the following Zenodo record:

> Daniel S. Himmelstein, Alexander R. Pico (2016) [**dhimmel/pathways v2.0: Compiling human pathway gene sets**](https://doi.org/10.5281/zenodo.48810) _Zenodo_. DOI: 10.5281/zenodo.48810 

In a text box I type `\cite{10.5281/zenodo.48810}` or use the citation import to retrieve its data metadata. The following BibTeX record is generated:

```
@data{2c5f44db-e2d3-465d-86b4-8dde3f6d92bc,
  doi = {10.5281/zenodo.48810},
  url = {http://dx.doi.org/10.5281/zenodo.48810},
  author = {Daniel S. Himmelstein; Alexander R. Pico;},
  publisher = {Zenodo},
  title = {{dhimmel/pathways v2.0: Compiling human pathway gene sets}},
  year = {2016},
}
```

The citation renders as `(Pico; 2016)` -- the first author does not appear first (or at all) and name are follwed by semicolons. I'm guessing this occurs since the records are retrieved from DataCite rather than CrossRef. Thus, authors are `; `-delimited rather than ` and `-delimited. Finially, having the generated BibTeX ID (`2c5f44db-e2d3-465d-86b4-8dde3f6d92bc`) is super unwieldy. If you're going to represent records with random characters, you might as well use the ID from [DOI shortening](http://shortdoi.org/).

**Comment by dhimmel** [comment]
Is there a publicly-available API for retrieving bibtex entries for DOIs in DataCite?

The [CrossRef Labs method](http://labs.crossref.org/citation-formatting-service/) doesn't work for Zenodo DOIs (I assume because they are only in DataCite not CrossRef). For example the following doesn't work:

```sh
curl -LH "Accept: text/bibliography; style=bibtex" http://dx.doi.org/10.5281/zenodo.48810
```

**Comment by mfenner** [comment]
Sorry, I should have been clearer: the citation keys in DataCite content negotiation is still a UUID, but we use the DOI expressed as URL in some other places.

> The CrossRef Labs method doesn't work for Zenodo DOIs (I assume because they are only in DataCite not CrossRef). For example the following doesn't work:

The official documentation for content negotiation is at http://crosscite.org/cn/. You should do the following:

```
curl -LH "Accept: application/x-bibtex" http://dx.doi.org/10.5281/zenodo.48810
```

As you note, there is another problem with DataCite bibtex: author names are not parsed correctly.

Both fixes (uuid and names) are our todo list, but unfortunately there are other things with higher priority, so it will be a few months before this is fixed.

**Comment by dhimmel** [comment]
> Both fixes (uuid and names) are our todo list, but unfortunately there are other things with higher priority

Okay I will do post-processing to modify the citation key and author list for DataCite records? Is there an easy another command to find out the registration agency of a given DOI, so I know whether to do post-processing?

**Comment by mfenner** [comment]
I use a Crossref API to look up the registration agency:

```
http://doi.crossref.org/doiRA/10.5281/zenodo.48810
```

You could use another format from the DOI content negotiation and convert to bibtex yourself. I don't know what tools or language you use, but Citeproc JSON is a good starting point:

```
curl -LH "Accept: application/vnd.citationstyles.csl+json" http://dx.doi.org/10.5281/zenodo.48810
```

**Comment by dhimmel** [comment]
@mfenner, good to know about the JSON format.

I ended up writing a [some Python](https://gist.github.com/dhimmel/719fc5e3a21dd2779d9fe69bf41e6ba6/34cb3b10ebe25cb424c1506172857c6f2c307d26) to perform the following for a DOI:

+ Retrieve bibtex using content negotiation
+ Fix DataCite `authors` formatting
+ Change all citation keys to short DOIs.

So people can use this in the meantime until DataCite gets around to these issues.

**Comment by mfenner** [comment]
Thanks @dhimmel !

**Comment by yarikoptic** [comment]
Thank you @dhimmel for forwarding me to this issue.  My question is either `@data` is anyhow "standard" record type in BibTeX?
I don't know if any "standard" really exists besides of what was implemented in original bibtex but e.g. looking at https://www.cs.arizona.edu/~collberg/Teaching/07.231/BibTeX/bibtex.html , I have never seen `@data` records.  So couldn't `@misc` be used instead -- seems to encapsulate similar notion of "I don't know what this records is about exactly", since now `@data` is also referencing software, datasets, whatever ?

**Comment by dhimmel** [comment]
Apologies for making this issue explode into "BibTeX and DataCite." Let us know when to start a new issue.

> So couldn't `@misc` be used instead

Especially in the case where the record is not known to be data, I think `@misc` would be more appropriate. 

@yarikoptic, regarding what types are standard, [here is the set](https://github.com/sciunto-org/python-bibtexparser/blob/5bc5264fe35bf5bbba072f10e0c3996cf760383b/bibtexparser/bibdatabase.py#L11) adopted by `bibtexparser` in python. For my use case, it took a while to figure out that I had to specify `ignore_nonstandard_types=False` in the `bibtexparser` parser to accept the `@data` type. So I'm not surprised if DataCite's `@data` type is causing many users problems.

**Comment by yarikoptic** [comment]
I think that `@misc` would be appropriate for any of those cases, probably even including data.  E.g. `howpublished` field could be used to designate between software/data/... without causing incompatibilities with existing bibtex and possible latex processors

**Comment by yarikoptic** [comment]
`Let us know when to start a new issue.`
What about a PR instead?;)  https://github.com/datacite/content-resolver/pull/24
